name: PaperMail
main: com.github.derwisch.paperMail.PaperMail
version: 1.0.1.4
load: POSTWORLD
commands:
   papermail:
      usage: /papermail <sendtext|createbox>
      aliases: [pm]
      
permissions:
    papermail.*:
        description: Gives access to all PaperMail functionallity
        children:
            papermail.send.text: true
            papermail.send.item.box: true
            papermail.createchest.self: true
            papermail.createchest.everyone: true
    papermail.send.text:
        description: Allows to send textmails
        default: true
    papermail.send.item:
        description: Allows to send papermails via a mailbox
        default: true
    papermail.createchest.self:
        description: Allows to create mailbox chests for the player
        default: true
    papermail.createchest.everyone:
        description: Allows to create mailbox chests for everyone
        default: false
        children:
            papermail.createchest.self: true
        
